ssi-dk/diseasystore

- R/0_documentation.R
- R/DiseasystoreBase.R
- R/DiseasystoreGoogleCovid19.R
- R/aggregators.R
- R/feature_store_helpers.R
- man/DiseasystoreBase.Rd
- man/DiseasystoreGoogleCovid19.Rd
- man/aggregators.Rd
- man/diseasystore_case_definition.Rd
- man/diseasystore_exists.Rd
- man/get_diseasystore.Rd
fixes Replace roxygen templates with inline templates #17
> feat: use inline templates instead of roxygen templates

- tests/testthat/test-non_ascii.R
> Test for non-ascii characters

- R/truncate_interlace.R
> fix: edge case in truncate_interlace

- DESCRIPTION
- R/0_R6_utils.R
- R/DiseasystoreBase.R
- R/DiseasystoreGoogleCovid19.R
- README.md
- man/diseasystore-package.Rd
- tests/testthat/test-0_R6_utils.R
- tests/testthat/test-0_documentation.R
This PR does a few small things.
It adds a parser for a conn option.
It updates the install instructions in the README
it adds a test of the rd_templates
It converts package title to Title Case
> Add utility functions and other misc.

- .github/workflows/render-readme.yaml
- README.Rmd
- README.md
This PR implements RMarkdown README.md from ssi-dk/SCDB
> docs: use RMarkdown to render README.md

- R/DiseasystoreBase.R
- R/drop_diseasystore.R
- tests/testthat/test-0_R6_utils.R
- tests/testthat/test-DiseasystoreBase.R
- tests/testthat/test-DiseasystoreGoogleCovid19.R
- tests/testthat/test-drop_diseasystore.R
> Improve test coverage

- .Rbuildignore
- R/DiseasystoreBase.R
This PR fixes #39 related to the new API of `SCDB::update_snapshot` that was changed in SCDB v0.2
`diseasystores` calls to `SCDB::update_snapshot` now supplies a configured `Logger` 
N/A
> Adapt to SCDB v0.2

- R/DiseasystoreBase.R
- R/truncate_interlace.R
fixes #46 
Adds a warning if there is overlap in `names(observable_data)` and `aggregation_features`
N/A
> feat: add warning when stratification exists in observable

- R/DiseasystoreBase.R
- R/DiseasystoreGoogleCovid19.R
- man/DiseasystoreBase.Rd
This PR improves the control of the output from the `diseasystores` by adding an option that controls the `verbose` parameter 
Added the option `options("diseasystore.verbose" = TRUE)`
In addition, I reformatted the options by wrapping the names in quotes.
N/A
> feat(DiseasystoreBase): add a verbosity option

- DESCRIPTION
- R/DiseasystoreGoogleCovid19.R
- tests/testthat/test-DiseasystoreGoogleCovid19.R
Fixes #60 
Before, the code assumed `source_conn` was a directory.
This is now changed by doing the following:
1) Validate that `source_conn` is either a directory or a URL
2) Determine the location of `by-age.csv` depending on whether `source_conn` is URL or directory
N/A
> fix(DiseasystoreGoogleCovid19): allow URLs as source_conn

- R/DiseasystoreBase.R
Fixes #70
replaced `<` with `<=` in filtering of pre computed features
N/A
> Properly merge computed features with pre-computed features

- R/DiseasystoreBase.R
As per the documentation standard, functions should have explicit `return()`
This PR adds a `return()` statement to `get_feature`
N/A
N/A
> chore(DiseasystoreBase): explicitly return in get_results

- R/DiseasystoreBase.R
This PR fixes code issues with `DiseasystoreBase$determine_new_ranges()`
* Added visible binding to `DiseasystoreBase$determine_new_ranges()`
* Added a roxygen-like documentation to the function
Parts of `DiseasystoreBase$determine_new_ranges()` will be removed when data base locks are added (#77). 
Visible binding was not added to these parts (parts involving `potentially_ongoing`)
> feat(determine_new_ranges): improve docs and add visible binding

- R/DiseasystoreGoogleCovid19.R
This PR fixes #40 
Logic checks in `DiseasystoreGoogleCovid19` were updated with `purrr::none` to handle multiple aggregations
N/A
> fix: update logic in DiseasystoreGoogleCovid19$key_join_filter

- R/DiseasystoreBase.R
This PR changes the loading of `source_conn` and `target_conn` such that they are always parsed
Small changes to the order of operations when loading conns in `initialize`
N/A
> Always parse source_conn and target_conn during initialize

- R/0_R6_utils.R
This PR fixes a small issue with `diseasyoption`.
The logic checking if the option is unset (i.e. = "") fails if the option contains a list.
The logic checking whether the option is unset is updated to use `identical` instead of `is.character(.) 
&& . == ""`
This logic works more generally with the any given input
N/A
> fix(diseasyoption): allow lists as diseasyoptions

- tests/testthat/test-0_examples.R
- tests/testthat/test-0_non_ascii.R
- tests/testthat/test-0_return.R
Tests that look at .R and .Rd files does not work in all cases.
The problem stems from folder structure differences between `devtools::test()`. `devtools::check()`, and GitHub workflows.
This PR makes the tests account for these differences, so they are run in all cases (and gives errors if not running)
The tests now uses regex parsing of the working path to determine the location of the directories where .Rd files and .Rd files are located
For `devtools::check()` and Github workflows, the .Rd files are stored in .rdx objects instead of plaintext, so these are loaded
instead of trying to read non existing .Rd files.
N/A
> Fix documentation and ASCII tests

- R/DiseasystoreBase.R
Recently, a new message has popped up inform that `names()` on some objects is for internal use only and to use `colnames()` instead.
This PR impelments this change.
N/A
N/A
> chore(DiseasystoreBase): use colnames instead of names

- R/DiseasystoreBase.R
Default option "lock_max_wait" does not match the option used in the code ("lock_wait_max")
This PR fixes this
N/A
N/A
> fix(DiseasystoreBase): fix mismatched lock_wait_max option

- .Rbuildignore
- .gitignore
- DESCRIPTION
- tests/testthat/.gitignore
- tests/testthat/setup.R
- tests/testthat/test-0_R6_utils.R
- tests/testthat/test-DiseasystoreBase.R
- tests/testthat/test-DiseasystoreGoogleCovid19.R
- tests/testthat/test-drop_diseasystore.R
- tests/testthat/test-zzz.R
Fixes #80 
Options now set with `withr::local_options`
Test added (`test-zzz.R`) that confirms that options related to `diseasy*` are not changed during the tests
`devtools::package_file`  replaced with `testthat::test_path` which solved `Suggests:` package dependency issue
N/A
> test: use local options + improve formatting

- .github/workflows/all-workflows.yaml
Workflows does not trigger on push to main. This PR intends to fix this
Adjust the if: logic for the workflow
N/A
> Adjust workflow triggering on push

- R/0_locks.R
- R/DiseasystoreBase.R
- tests/testthat/test-DiseasystoreGoogleCovid19.R
This PR is intended to work as a stop gap measure for issue #113.
Currently, I believe issue #113 is due to a lot of `dbplyr_###` tables being created and not deleted in our processes.
These are deleted once the connections are closed, but if too many operations are done on a connection before closing it, we
seemingly get intermittent issues.
This PR introduces
1) some clean up of  `dbplyr_###` tables to the functions we control
2) during clean up, a potentially unsafe usage of the "ds_tmp" table was identified. To mitigate risks of overwriting this table, more specific temporary tables are used giving each thread their own tables. (fixes #74) 
3) clean up `dbplyr_###` tables during tests
N/A
> Improve test stability

- .github/workflows/all-workflows.yaml
- DESCRIPTION
- NEWS.md
- R/0_locks.R
- R/DiseasystoreBase.R
- cran-comments.md
- tests/testthat/setup.R
- tests/testthat/test-DiseasystoreGoogleCovid19.R
- vignettes/diseasystore-google-covid-19.Rmd
- vignettes/diseasystore.Rmd
- vignettes/extending-diseasystore.Rmd
This PR tracks the final changes before submitting v0.1.1 to CRAN
Multiple minor adjustments. See commits.
N/A
> Prepare for release of v0.1.1

- DESCRIPTION
- NEWS.md
- R/0_R6_utils.R
- R/DiseasystoreGoogleCovid19.R
- inst/WORDLIST
- man/diseasyoption.Rd
- man/diseasystore-package.Rd
- tests/testthat/test-0_R6_utils.R
- tests/testthat/test-DiseasystoreGoogleCovid19.R
- vignettes/diseasystore.Rmd
This small PR adds a default value to `diseasyoption` via the `.default` argument.
(inspired by `purrr::pluck()`)
N/A
N/A
> Add default value to diseasyoption

- R/0_documentation.R
- README.Rmd
- README.md
Quick fix of spelling
Edited the spelling
N/A
> docs(README): fix spelling

- .Rbuildignore
- R/test_diseasystore.R
- tests/testthat/test-DiseasystoreBase.R
- vignettes/diseasystore-ecdc-respiratory-viruses.Rmd
- vignettes/diseasystore-google-covid-19.Rmd
This PR contains the final changes needed to release v0.2
N/A
N/A
> Add v0.2 release

- R/grapes-.-grapes.R
- pak.lock
- tests/testthat/test-grapes-.-grapes.R
This PR tests that `%.%` works for nested data structures and improves the error message when
a object is not found.
Test cases expanded with nested data structures
The error message now uses `match.call()` to determine a good format for the `env` name
N/A
> feat(%.%): Improve for nested structures

- NEWS.md
- R/grapes-.-grapes.R
- pak.lock
- tests/testthat/test-grapes-.-grapes.R
Ideally `%.%` should be a drop-in replacement for `$`.
This PR allows for more general use of `%.%` which I have encountered during development.
We now also capture call on the field to extract and evoke this call after extracting the object.
A unnecessary conversion from environment to list is now omitted as it caused problems in some cases with R6 objects.
N/A
> Allow `%.%` to be used in any context

- tests/testthat/test-truncate_interlace.R
fixes #148 
We check for equality of data in `truncate_interlace`. 
Sometimes databases changes the order of records, so we sort before comparing.
N/A
> test(truncate_interlace): Sort before checking for equality

- pak.lock
- vignettes/diseasystore.Rmd
This small PR removes a lot of confusing output from the "Dropping computed features" section
https://ssi-dk.github.io/diseasystore/articles/diseasystore.html#dropping-computed-features
Temporary tables were removed from the output with `show_temporary = FALSE`
The section now renders like this:
N/A
> Minor improvements to Get Started vignette

- R/DiseasystoreBase.R
- pak.lock
> chore(DiseasystoreBase): Use `imap` instead of `map2`

- R/0_R6_utils.R
- pak.lock
- tests/testthat/test-0_R6_utils.R
Make the failure messages from `parse_diseasyconn()` more specific.
The type of connection that could not be parsed is now included in the error message
N/A
> fix(parse_diseasyconn): Improve error messages when failing to parse

- R/DiseasystoreBase.R
- man/DiseasystoreBase.Rd
This PR sets the default `stratification` in `$key_join_features()` to `NULL`  and documents
that this means no stratification is done.
This enables a better user interface where this code:
```
ds$key_join_features(
observable = "n_positive",
stratification = NULL,
start_date = ds$min_start_date,
end_date = ds$max_end_date
)
```
Can be simplified to:
```
ds$key_join_features(
observable = "n_positive",
start_date = ds$min_start_date,
end_date = ds$max_end_date
)
```
N/A
N/A
> `$key_join_features()`: Use no stratification by default

- NEWS.md
- R/test_diseasystore.R
- pak.lock
This PR fixes a small issue in `test_diseasytore()`.
Here, we assert that the object being tested is a `diseasystore` which here means that it inherits from `DiseasystoreBase`. 
Before, this had to be explicitly written as 
```
DiseasystoreTest <- R6::R6Class(
...
inherit = DiseasytoreBase
...
)
```
But then when working outside of `diseasystore`, we may want to write:
```
DiseasystoreTest <- R6::R6Class(
...
inherit = diseasytore::DiseasytoreBase
...
)
```
or we may even want to have nested inheritance
`DiseasystoreBase -> DiseasystoreGeneric -> DiseasytoreSpecifc`
This PR allows this behaviour
~~The assertion of the inheritance is made more flexible by regex.~~
~~Now we require the inherit field to contain "DiseasytoreBase"~~
The assertion of the inheritance has been removed
N/A
> fix(test_diseasystore): Remove check that objects are diseasystores

- NEWS.md
- R/DiseasystoreBase.R
- pak.lock
When creating very simple feature stores, where features are not separated into different tables, there is a bug in how the data is returned from the `$key_join_features`.
If a feature, say "age_group", exists in the `observable_data` and the user requests it as a stratification, then `$key_join_features` will currently pull the table again as one of the `stratification_data` and merge these tables together.
This normally works well, since the features are assumed to be in separate tables, but in this case, they are in the same table, and the join duplicates the rows.
This PR prevents this issue
The order of operations have been changed so that we now first compute the `observable_data` before the `stratification data`
If a requested stratification is already in `observable_data` we do …
> Discard stratification data if already in observable data

- .github/sync.yaml
Add the file `R/0_miscellaneous.R` to the Sync workflow and sync with SCDB
N/A
N/A
> Update sync workflow

- R/0_documentation.R
- R/0_linters.R
- R/DiseasystoreBase.R
- R/drop_diseasystore.R
- R/source_conn_helpers.R
- R/test_diseasystore.R
- man/DiseasystoreBase.Rd
- man/drop_diseasystore.Rd
- man/source_conn_helpers.Rd
- man/test_diseasystore.Rd
- pak.lock
- tests/testthat/test-0_linters.R
With the recent merge of https://github.com/ssi-dk/diseasy/pull/126, we now have linter that checks for the usage of the documentation templates.
This PR adds the linter to `diseasystore` and fixes the lints that are introduced by incorporating the documentation templates where available.
Templates are combined with the existing documentation.
In some cases, the templates are updated.
In addition, other lints are fixed
N/A
> Use documentation templates
